Token transfer custom gateway
LighthouseWeb3/files-dapp pull request #10
Opened 2022-04-15 23:54 UTC by arpitB-dev

2022-04-18 02:01 UTC, ravish1729 requested changes
See comments in respective files.

2022-04-18 20:32 UTC, arpitB-dev commented on src/utils/config/tokenTransferData.js
> +  "https://api.bscscan.com/api?module=contract&action=getabi&address=0x55d398326f99059fF775485246999027B3197955&apikey=H2JKE5NV61GF5A1XZ7Z8X79VKGDJ2A1KNW";
done

2022-04-19 08:07 UTC, ravish1729 requested changes
Minor updates needed

2022-04-19 08:07 UTC, ravish1729 commented on src/utils/config/tokenTransferData.js
> +export const abiURL =
has to be removed, abi URL. Import abi file wherever needed

2022-04-19 08:07 UTC, ravish1729 commented on src/utils/services/transferUSDC.js
> +  abiURL,
again abi file insted of url

2022-04-19 12:03 UTC, nandit123 commented on src/pages/adminPanel/TopUp/TopUp.jsx
> +            <div className="planCard">
change UI for topup as discussed

2022-04-19 12:04 UTC, nandit123 commented on src/utils/config/tokenTransferData.js
> +export const abiURL =
good catch

2022-04-19 12:07 UTC, nandit123 requested changes
To correct changes pointed by ravish, rest LGTM

2022-04-19 20:25 UTC, arpitB-dev commented on src/utils/services/transferUSDC.js
> +  abiURL,
done

2022-05-04 10:20 UTC, closed without merging